version: '3.8'

services:
  app:
    build: .
    container_name: app
    environment:
      - NODE_ENV=production
    # volumes:
    #   - static_value:/app/.next/static/
      # - media_value:/app/.next/media/

  nginx:
    image: nginx:1.25.4-alpine
    container_name: nginx
    ports:
      - "80:80"
      # Для HTTPS порт
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.next:/usr/share/nginx/html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_value:
  media_value:
