networks:
  talent_reserves_default:

services:
  app:
    container_name: talent_reserves-front
    image: leonid89/talent_reserves-front:latest 
    environment:
      - NODE_ENV=production
    networks:
      - talent_reserves_default

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.next:/usr/share/nginx/html
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - talent_reserves_default
