networks:
  db_network:

volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

  backend:
    container_name: talent_reserves-back
    image: leonid89/talent_reserves-back:latest
    env_file: .env
    command: gunicorn talent_reserves.wsgi:application --bind 0:8000
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - db
      - redis
    networks:
      - db_network
  
  # celery:
  #   build: talent_reserves
  #   command: celery -A talent_reserves worker -l INFO
  #   env_file: .env
  #   depends_on:
  #     - backend
  #   networks:
  #     - db_network

  # redis:
  #   restart: always
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   command: redis-server
  #   networks:
  #     - db_network
  
  frontend:
    container_name: talent_reserves-front
    image: leonid89/talent_reserves-front:latest
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    container_name: talent_reserves-proxy
    image: leonid89/talent_reserves-proxy:latest
    ports:
      - 8000:80 
    volumes:
      - ../frontend/.next:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    networks:
      - db_network
