volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../talent_reserves
    command: gunicorn talent_reserves.wsgi:application --bind 0.0.0.0:8000
    env_file: ../.env
    volumes:
      - static:/app/staticfiles
      - media:/app/mediafiles
    depends_on:
      - db
      - redis

  celery:
    build: ../talent_reserves
    command: celery -A talent_reserves worker -l INFO
    env_file: ../.env
    depends_on:
      - backend

  redis:
    image: "redis:alpine"

  nginx:
    image: nginx:1.19.3
    ports:
      - 8000:8000
    volumes:
       - static:/staticfiles
       - media:/mediafiles
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
