volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
        - db_network

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - db_network

  backend:
    build: ../talent_reserves
    command: gunicorn talent_reserves.wsgi:application --bind 0.0.0.0:8000
    env_file: ../.env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - db_network
    

  celery:
    build: ../talent_reserves
    command: celery -A talent_reserves worker -l INFO
    env_file: ../.env
    depends_on:
      - backend
      - redis
    networks:
      - db_network

networks:
  db_network:
