version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build: ./talent_reserves
    command: gunicorn talent_reserves.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
